# Generated by Django 4.1.3 on 2023-11-27 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('instructors', models.CharField(max_length=100)),
                ('days_week', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('open_class', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('modularity', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_courses', models.ManyToManyField(to='scraper.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
